add contributors bot

diff --git a/.github/workflows/Lint.yml b/.github/workflows/Lint.yml
--- a/.github/workflows/Lint.yml
+++ b/.github/workflows/Lint.yml
@@ -8,8 +8,6 @@ on:
   pull_request:
 
 concurrency:
-  # Skip intermediate builds: always.
-  # Cancel intermediate builds: only if it is a pull request build.
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
 
@@ -20,25 +18,37 @@ jobs:
     steps:
       - name: Clone
         uses: actions/checkout@v4
+
       - name: Setup Julia
         uses: julia-actions/setup-julia@v2
         with:
           version: "1"
+
       - name: Use Julia cache
         uses: julia-actions/cache@v2
+
       - name: Install JuliaFormatter.jl
         run: julia -e 'using Pkg; pkg"add JuliaFormatter"'
+
+      - name: Check Julia code formatting
+        run: |
+          julia --project=. -e 'using JuliaFormatter; format(["src", "test", "docs"])'
+          git diff --exit-code || (echo "ERROR: Code is not properly formatted. Please run JuliaFormatter locally." && exit 1)
+
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
           cache: "pip"
+
       - name: Cache pre-commit
         uses: actions/cache@v4
         with:
           path: ~/.cache/pre-commit
           key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
+
       - name: Install pre-commit
         run: pip install pre-commit
+
       - name: Run pre-commit
         run: SKIP=no-commit-to-branch pre-commit run -a
 
